"""Stage a trimmed copy of the upstream ``wechatauto`` package for packaging.

Why this exists
---------------
The upstream ``wechatauto-replica`` distribution is installed *editable* in the
build environment, which PyInstaller's static analysis cannot follow.  Worse,
its ``__init__.py`` eagerly imports the whole automation surface (message
sending, moments, UIA drivers).  Bundling that would:

* make the "read-only Beta" carry write-capable code paths, contradicting the
  project's core safety stance; and
* bloat the artifact with dependencies the read-only flow never touches.

This script copies **only** the two modules the project actually imports —
``db`` and ``media`` — plus a minimal ``__init__.py`` into a staging directory.
The spec then puts that staging root on ``pathex`` so PyInstaller packages a
trimmed ``wechatauto`` package and still resolves ``wechatauto.db`` /
``wechatauto.media`` at runtime.

The upstream LICENSE is copied alongside so it can be bundled verbatim.

Usage::

    python packaging/stage_upstream.py            # write staging dir
    python packaging/stage_upstream.py --clean    # remove it

Programmatic use: ``stage()`` returns the staging root ``Path``.
"""

from __future__ import annotations

import argparse
import importlib.util
import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
STAGING_DIR = REPO_ROOT / "build" / "upstream-staging"

# Only the modules the read-only flow imports.  Keep this list minimal and
# update it only with a matching safety review.
ALLOWED_MODULES = ("db.py", "media.py")

# A permissive __init__ that deliberately does NOT import the automation surface.
PACKAGE_INIT = '''"""Trimmed upstream package staged for the read-only Beta build.

This is generated by ``packaging/stage_upstream.py``.  Unlike the upstream
``__init__.py`` it does not import message sending, moments or UIA drivers, so a
frozen read-only Beta cannot reach write-capable code paths through this package.
"""

from __future__ import annotations

from .db import WeChatDB, auto_detect_db_dir, list_accounts
from .media import MediaDownloader

__all__ = [
    "MediaDownloader",
    "WeChatDB",
    "auto_detect_db_dir",
    "list_accounts",
]
'''


def locate_upstream_package() -> Path:
    """Return the installed ``wechatauto`` package directory.

    Handles both a normal install (``__file__`` points inside site-packages) and
    an editable install (PEP 660 ``__editable__`` finder mapping).
    """
    spec = importlib.util.find_spec("wechatauto")
    if spec is None:
        raise SystemExit(
            "wechatauto is not importable in this interpreter; "
            "build from the environment that has it installed"
        )
    if spec.origin and spec.origin.endswith("__init__.py"):
        return Path(spec.origin).parent

    # Editable install: resolve through the finder's package search path.
    if spec.submodule_search_locations:
        first = next(iter(spec.submodule_search_locations))
        candidate = Path(first)
        if candidate.is_dir():
            return candidate

    raise SystemExit(f"could not resolve the wechatauto package directory (spec={spec!r})")


def stage() -> Path:
    """Create the trimmed staging package and return its parent directory.

    Staging is **idempotent and additive**: existing files are overwritten in
    place rather than the tree being removed first.  Bulk directory removal is
    deliberately avoided — it is an operation this project keeps under explicit
    human control, and a build helper has no business performing one.
    """
    source_pkg = locate_upstream_package()
    target_pkg = STAGING_DIR / "wechatauto"
    target_pkg.mkdir(parents=True, exist_ok=True)

    # Minimal, read-only __init__ (overwrites any previous copy).
    (target_pkg / "__init__.py").write_text(PACKAGE_INIT, encoding="utf-8")

    copied: list[str] = []
    for name in ALLOWED_MODULES:
        src = source_pkg / name
        if not src.is_file():
            raise SystemExit(f"expected upstream module missing: {src}")
        shutil.copy2(src, target_pkg / name)
        copied.append(name)

    # Preserve the trailing files the upstream project ships inside the package.
    typed = source_pkg / "py.typed"
    if typed.is_file():
        shutil.copy2(typed, target_pkg / "py.typed")

    # Upstream license travels with the staged copy for traceability.
    license_candidates = (
        source_pkg.parent / "LICENSE",
        source_pkg / "LICENSE",
    )
    for license_path in license_candidates:
        if license_path.is_file():
            shutil.copy2(license_path, STAGING_DIR / "wechatauto-replica-LICENSE.txt")
            break

    print(f"[stage] upstream package: {source_pkg}")
    print(f"[stage] staged {len(copied)} module(s): {', '.join(copied)}")
    print(f"[stage] staging root: {STAGING_DIR}")
    return STAGING_DIR


def clean() -> None:
    """Remove only the files this script created, one at a time."""
    target_pkg = STAGING_DIR / "wechatauto"
    removed = 0
    for name in (*ALLOWED_MODULES, "__init__.py", "py.typed"):
        candidate = target_pkg / name
        if candidate.is_file():
            candidate.unlink()
            removed += 1
    license_copy = STAGING_DIR / "wechatauto-replica-LICENSE.txt"
    if license_copy.is_file():
        license_copy.unlink()
        removed += 1
    print(f"[stage] removed {removed} staged file(s) from {STAGING_DIR}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--clean", action="store_true", help="remove the staging directory")
    args = parser.parse_args(argv)
    if args.clean:
        clean()
        return 0
    stage()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
